version: "3.1"

services:
  minio:
    image: minio/minio
    hostname: minio
    container_name: minio
    restart: always
    ports:
      - 9000:9000
    command: ["server", "/data"]
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
